# Adopt from https://github.com/starkat99/appveyor-rust

## Operating System (VM environment) ##

# Rust needs at least Visual Studio 2013 Appveyor OS for MSVC targets.
os: Visual Studio 2015

## Build Matrix ##
environment:
    matrix:

        # use MSVC toolchains

        # Stable 64-bit MSVC
        - channel: stable
          target: x86_64-pc-windows-msvc
        # Stable 32-bit MSVC
        - channel: stable
          target: i686-pc-windows-msvc
        # Nightly 64-bit MSVC
        - channel: nightly
          target: x86_64-pc-windows-msvc
        # Nightly 32-bit MSVC
        - channel: nightly
          target: i686-pc-windows-msvc
        # Lowest supported version 64-bit MSVC
        - channel: 1.14.0
          target: x86_64-pc-windows-msvc
        # Lowest supported version 32-bit MSVC
        - channel: 1.14.0
          target: i686-pc-windows-msvc

## Install Script ##

install:
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -yv --default-toolchain %channel% --default-host %target%
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    - rustc -vV
    - cargo -vV

## Build Script ##

build_script:
    - cargo build --release --verbose %cargoflags%

# Uses 'cargo test' to run tests and build. Alternatively, the project may call compiled programs
#directly or perform other testing commands. Rust will automatically be placed in the PATH
# environment variable.
test_script:
    - cargo test --verbose %cargoflags%

cache:
    - '%USERPROFILE%\.cargo\registry'
    - target
