[package]
name = "symrs"
version = "0.0.0"
authors = ["Peng Guanwen <pgw1999@outlook.com>"]
description = "Symbolic computation in Rust"
repository = "https://github.com/peng1999/symrs"

[dependencies]
lazy_static = "0.2"
num = "0.1"
symtern = "0.1"
itertools = "0.7"
