[tasks.release-test]
env = { RUSTFLAGS = "--cfg check_doc" }
run_task = "test"

[tasks.test]
dependencies = [
    "check",
    "check-examples",
    "clippy",
]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.check-examples]
command = "cargo"
args = ["check", "--examples"]
